dist: bionic
language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get -y install cmake ocl-icd-opencl-dev

install:
  - git clone git://github.com/shamazmazum/program-map.git program-map
  - pushd program-map && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make && sudo make install
  - popd

before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX:PATH=$TRAVIS_BUILD_DIR/build/install $TRAVIS_BUILD_DIR

script:
  - make
  - sudo make install
